pipeline {
    agent {
        docker {
            image 'openjdk:11'
            args '-v $PWD:/app -w /app'
        }
    }
    stages {
        stage('Clone Repo') {
            steps {
                echo 'Assuming code is already present (in a Jenkinsfile inside repo)'
            }
        }

        stage('Compile') {
            steps {
                echo 'Compiling Java code...'
                sh 'javac Main.java'
            }
        }

        stage('Run') {
            steps {
                echo 'Running Java program...'
                sh 'java Main'
            }
        }
    }
}
